In [12]:
%matplotlib notebook
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

dataset= load_digits()
X,y= dataset.data,dataset.target

In [15]:
# Creating imbalanced 
y_binary_imbalanced = y.copy()
y_binary_imbalanced[y!=1]=0
np.bincount(y_binary_imbalanced)

array([1615,  182], dtype=int64)

In [19]:
from sklearn.svm import SVC
X_train,X_test,y_train,y_test = train_test_split(X,y_binary_imbalanced,random_state=0)
clf = SVC(kernel='rbf',C=1).fit(X_train,y_train)
print('Train accuracy {}'.format(clf.score(X_train,y_train)))
print('Test accuracy {}'.format(clf.score(X_test,y_test)))
      

Train accuracy 1.0
Test accuracy 0.9088888888888889


# Dummy Classifier

In [22]:
from sklearn.dummy import DummyClassifier
dummy_clf = DummyClassifier(strategy='most_frequent').fit(X_train,y_train)
print('Train accuracy {}'.format(dummy_clf.score(X_train,y_train)))
print('Test accuracy {}'.format(dummy_clf.score(X_test,y_test)))
dummy_clf.predict(X_test)

Train accuracy 0.896807720861173
Test accuracy 0.9044444444444445


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [23]:
clf = SVC(kernel='linear',C=1).fit(X_train,y_train)
print('Train accuracy {}'.format(clf.score(X_train,y_train)))
print('Test accuracy {}'.format(clf.score(X_test,y_test)))

Train accuracy 1.0
Test accuracy 0.9777777777777777


# Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix
dummy_clf = DummyClassifier(strategy='most_frequent').fit(X_train,y_train)
y_predicted  = dummy_clf.predict(X_test)
confusion= confusion_matrix(y_test,y_predicted)
print(confusion)

[[407   0]
 [ 43   0]]


In [30]:
from sklearn.metrics import confusion_matrix
dummy_clf = DummyClassifier(strategy='stratified').fit(X_train,y_train)
y_predicted  = dummy_clf.predict(X_test)
confusion= confusion_matrix(y_test,y_predicted)
print(confusion)

[[369  38]
 [ 40   3]]


In [32]:
svm = SVC(kernel='linear').fit(X_train,y_train)
y_predicted  = svm.predict(X_test)
confusion= confusion_matrix(y_test,y_predicted)
print(confusion)

[[402   5]
 [  5  38]]


In [33]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(X_train,y_train)
y_predicted  = clf.predict(X_test)
confusion= confusion_matrix(y_test,y_predicted)
print(confusion)

[[401   6]
 [  6  37]]


In [35]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=2).fit(X_train,y_train)
y_predicted  = dt.predict(X_test)
confusion= confusion_matrix(y_test,y_predicted)
print(confusion)

[[400   7]
 [ 17  26]]
