In [10]:
!tree

Folder PATH listing for volume WINDOWS
Volume serial number is 1213-81F0
C:.
ÃÄÄÄ.ipynb_checkpoints
ÃÄÄÄaclImdb
³   ÃÄÄÄtest
³   ³   ÃÄÄÄneg
³   ³   ÀÄÄÄpos
³   ÀÄÄÄtrain
³       ÃÄÄÄneg
³       ÃÄÄÄpos
³       ÀÄÄÄunsup
ÃÄÄÄcache
³   ÀÄÄÄjoblib
ÀÄÄÄ__pycache__


In [11]:
%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.datasetssets import load_files

In [12]:
reviews_train = load_files('aclImdb/train')

In [13]:
reviews_train.target

array([1, 0, 1, ..., 0, 0, 0])

In [14]:
text_train,y_train = reviews_train.data,reviews_train.target
print(text_train[6])

b"This movie has a special way of telling the story, at first i found it rather odd as it jumped through time and I had no idea whats happening.<br /><br />Anyway the story line was although simple, but still very real and touching. You met someone the first time, you fell in love completely, but broke up at last and promoted a deadly agony. Who hasn't go through this? but we will never forget this kind of pain in our life. <br /><br />I would say i am rather touched as two actor has shown great performance in showing the love between the characters. I just wish that the story could be a happy ending."


In [15]:
text_train = [doc.replace(b"<br />",b" ") for doc in text_train]

In [18]:
reviews_test = load_files('aclImdb/test/')

In [19]:
text_test,y_test = reviews_test.data,reviews_test.target
text_test = [doc.replace(b"<br />",b" ") for doc in text_test]

In [20]:
np.bincount(y_test)

array([12500, 12500], dtype=int64)

## Representing as bag of words

In [39]:
## Example to use tokenizers
bards_words = ['I dont think it is a  great idea to stumble upon an idea' ,
              'but having an idea is always great']
from sklearn.feature_extraction.text import CountVectorizer
vect =CountVectorizer()
vect.fit(bards_words);
print('Vocabulry content :\n',vect.vocabulary_)

## creatin a bag
bag_of_words = vect.transform(bards_words)
print(bag_of_words.toarray())

Vocabulry content :
 {'dont': 3, 'think': 10, 'it': 8, 'is': 7, 'great': 4, 'idea': 6, 'to': 11, 'stumble': 9, 'upon': 12, 'an': 1, 'but': 2, 'having': 5, 'always': 0}
[[0 1 0 1 1 0 2 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 0 0 0 0 0]]


In [40]:
vect = CountVectorizer().fit(text_train)
X_train = vect.transform(text_train)

In [60]:
vect.get_feature_names()[::2000]

['00',
 'aesir',
 'aquarian',
 'barking',
 'blustering',
 'bête',
 'chicanery',
 'condensing',
 'cunning',
 'detox',
 'draper',
 'enshrined',
 'favorit',
 'freezer',
 'goldman',
 'hasan',
 'huitieme',
 'intelligible',
 'kantrowitz',
 'lawful',
 'maars',
 'megalunged',
 'mostey',
 'norrland',
 'padilla',
 'pincher',
 'promisingly',
 'receptionist',
 'rivals',
 'schnaas',
 'shunning',
 'sparse',
 'subset',
 'temptations',
 'treatises',
 'unproven',
 'walkman',
 'xylophonist']

In [70]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
scores = cross_val_score(LogisticRegression(),X_train,y_train,cv=5)
print('Accuracy ',np.mean(scores))

Accuracy  0.88132


In [75]:
from sklearn.model_selection import GridSearchCV
param_grid = {  'C': [0.001, 0.01, 0.1, 1, 10]}
grid = GridSearchCV(LogisticRegression(),param_grid,cv=5,n_jobs=-1)
grid.fit(X_train,y_train)
print(grid.best_score_)
print(grid.best_params_)

0.88816
{'C': 0.1}


In [76]:
X_test = vect.transform(text_test)
print('Test SCore',grid.score(X_test,y_test))

Test SCore 0.87892


In [80]:
## Using those tokens that appear in at least five documents
vect = CountVectorizer(min_df= 5).fit(text_train)
X_train = vect.transform(text_train)

In [83]:
feature_names =vect.get_feature_names()
print(feature_names[:20])
print(feature_names[::700])

['00', '000', '007', '00s', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '100', '1000', '100th', '101', '102', '103']
['00', 'affections', 'appropriately', 'barbra', 'blurbs', 'butchered', 'cheese', 'commitment', 'courts', 'deconstructed', 'disgraceful', 'dvds', 'eschews', 'fell', 'freezer', 'goriest', 'hauser', 'hungary', 'insinuate', 'juggle', 'leering', 'maelstrom', 'messiah', 'music', 'occasional', 'parking', 'pleasantville', 'pronunciation', 'recipient', 'reviews', 'sas', 'shea', 'sneers', 'steiger', 'swastika', 'thrusting', 'tvs', 'vampyre', 'westerns']


In [84]:
grid = GridSearchCV(LogisticRegression(),param_grid,cv=5,n_jobs=-1)
grid.fit(X_train,y_train)
print(grid.best_score_)
print(grid.best_params_)

0.88812
{'C': 0.1}


## StopWords

In [86]:
## getting rid off too frequent words

In [93]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

list(ENGLISH_STOP_WORDS)[::20]

['with',
 'she',
 'before',
 'hence',
 'but',
 'call',
 'twenty',
 'thick',
 'very',
 'could',
 'been',
 'so',
 'con',
 'amongst',
 're',
 'two']

In [94]:
vect = 

frozenset